/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pbo;

/**
 *
 * @author necha
 */
public class Kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        absen = new javax.swing.JLabel();
        matpel = new javax.swing.JLabel();
        nilai = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        Nilai1 = new javax.swing.JTextField();
        Nama1 = new javax.swing.JTextField();
        Absen1 = new javax.swing.JTextField();
        Matpel1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Penilaian Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 90, 40);

        nama.setText("Nama");
        getContentPane().add(nama);
        nama.setBounds(50, 70, 60, 30);

        absen.setText("Absen");
        getContentPane().add(absen);
        absen.setBounds(50, 110, 60, 30);

        matpel.setText("Matpel");
        getContentPane().add(matpel);
        matpel.setBounds(50, 150, 60, 30);

        nilai.setText("Nilai");
        getContentPane().add(nilai);
        nilai.setBounds(50, 190, 60, 30);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(160, 240, 80, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 280, 240, 130);

        Nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nilai1ActionPerformed(evt);
            }
        });
        getContentPane().add(Nilai1);
        Nilai1.setBounds(110, 190, 170, 30);

        Nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(Nama1);
        Nama1.setBounds(110, 70, 170, 30);

        Absen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Absen1ActionPerformed(evt);
            }
        });
        getContentPane().add(Absen1);
        Absen1.setBounds(110, 110, 170, 30);

        Matpel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Matpel1ActionPerformed(evt);
            }
        });
        getContentPane().add(Matpel1);
        Matpel1.setBounds(110, 150, 170, 30);

        setBounds(0, 0, 416, 475);
    }// </editor-fold>//GEN-END:initComponents

    private void Nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nilai1ActionPerformed

    private void Nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama1ActionPerformed

    private void Absen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Absen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Absen1ActionPerformed

    private void Matpel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Matpel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Matpel1ActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
    String nama = Nama1.getText();
    String absen = Absen1.getText();
    String matpel = Matpel1.getText();
    int nilai = Integer.parseInt(Nilai1.getText());
    String Ket = " ";
    if(nilai<75){
        Ket = "Tidak Lulus";
    }
    if(nilai>=75){
        Ket = "Lulus";
    }
    if(nilai==100){
        Ket = "Sempurna";
    }
    else if(nilai>100){
        Ket = "Amazing";
    
    }//GEN-LAST:event_btnProsesActionPerformed
    TA.setText("Nama siswa :"+nama+"\nAbsen siswa :"+absen+"\nMatpel :"+matpel+"\nNilai :"+nilai+"\nKeterangan :"+Ket);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen1;
    private javax.swing.JTextField Matpel1;
    private javax.swing.JTextField Nama1;
    private javax.swing.JTextField Nilai1;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel absen;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel matpel;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nilai;
    // End of variables declaration//GEN-END:variables
}
