/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pbo;

import javax.swing.JOptionPane;

/**
 *
 * @author necha
 */
public class Lat3 extends javax.swing.JFrame {

    /**
     * Creates new form Lat3
     */
    public Lat3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panjang = new javax.swing.JLabel();
        lebar = new javax.swing.JLabel();
        tinggi = new javax.swing.JLabel();
        jPanjangBalok = new javax.swing.JTextField();
        jLebarBalok = new javax.swing.JTextField();
        jTinggiBalok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sisi = new javax.swing.JLabel();
        jSisiKubus = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jarijari = new javax.swing.JLabel();
        BtnBola = new javax.swing.JButton();
        jJariBola = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program Pencari Volume Bangun Ruang ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 240, 40);

        jPanel1.setLayout(null);

        panjang.setText("Masukkan Panjang :");
        jPanel1.add(panjang);
        panjang.setBounds(20, 20, 120, 30);

        lebar.setText("Masukkan Lebar     :");
        jPanel1.add(lebar);
        lebar.setBounds(20, 60, 120, 30);

        tinggi.setText("Masukkan Tinggi     :");
        jPanel1.add(tinggi);
        tinggi.setBounds(20, 100, 120, 30);

        jPanjangBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanjangBalokActionPerformed(evt);
            }
        });
        jPanel1.add(jPanjangBalok);
        jPanjangBalok.setBounds(140, 20, 120, 30);
        jPanel1.add(jLebarBalok);
        jLebarBalok.setBounds(140, 60, 120, 30);
        jPanel1.add(jTinggiBalok);
        jTinggiBalok.setBounds(140, 100, 120, 30);

        jLabel11.setText("cm");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 20, 40, 30);

        jLabel12.setText("cm");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 60, 40, 30);

        jLabel13.setText("cm");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(270, 100, 40, 30);

        BtnBalok.setText("Hitung");
        BtnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBalok);
        BtnBalok.setBounds(140, 150, 120, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        sisi.setText("Masukkan Panjang Sisi");
        jPanel2.add(sisi);
        sisi.setBounds(20, 20, 150, 30);
        jPanel2.add(jSisiKubus);
        jSisiKubus.setBounds(20, 50, 120, 30);

        jLabel7.setText("cm");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(150, 50, 40, 30);

        BtnKubus.setText("Volume");
        BtnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(BtnKubus);
        BtnKubus.setBounds(20, 100, 120, 23);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jarijari.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jarijari);
        jarijari.setBounds(20, 20, 150, 30);

        BtnBola.setText("Volume");
        BtnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(BtnBola);
        BtnBola.setBounds(20, 100, 120, 23);

        jJariBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJariBolaActionPerformed(evt);
            }
        });
        jPanel3.add(jJariBola);
        jJariBola.setBounds(20, 50, 120, 30);

        jLabel6.setText("cm");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(150, 50, 40, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 400, 230);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBalokActionPerformed
    int panjang,lebar,tinggi;
    panjang=Integer.parseInt(jPanjangBalok.getText());
    lebar=Integer.parseInt(jLebarBalok.getText());
    tinggi=Integer.parseInt(jTinggiBalok.getText());
    int hasil=panjang*lebar*tinggi;
    try{
        JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error :"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_BtnBalokActionPerformed

    private void BtnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKubusActionPerformed
    int sisi;
    sisi=Integer.parseInt(jSisiKubus.getText());
    int hasil=sisi*sisi*sisi;
    
    try{
        JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error :"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_BtnKubusActionPerformed

    private void BtnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBolaActionPerformed
    float jari;
    jari=Integer.parseInt(jJariBola.getText());
    float hasil1=(float)(4/3*3.14*jari*jari*jari);
    try{
        JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah :"+hasil1,"luas",
                JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error :"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_BtnBolaActionPerformed

    private void jJariBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJariBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJariBolaActionPerformed

    private void jPanjangBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPanjangBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanjangBalokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lat3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lat3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBalok;
    private javax.swing.JButton BtnBola;
    private javax.swing.JButton BtnKubus;
    private javax.swing.JTextField jJariBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLebarBalok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPanjangBalok;
    private javax.swing.JTextField jSisiKubus;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTinggiBalok;
    private javax.swing.JLabel jarijari;
    private javax.swing.JLabel lebar;
    private javax.swing.JLabel panjang;
    private javax.swing.JLabel sisi;
    private javax.swing.JLabel tinggi;
    // End of variables declaration//GEN-END:variables
}
